### ISSUE TITLE
editDialogServer() function is missing

### ISSUE THREAD

**Issue by ddbs** [beerda/crudtable#1]
´editDialogServer()´ function is mentioned in ´/examples´ and in ´validator.R´  but is non-existing

`> runApp('inst/examples/basic')
Error in editDialogServer(dao$getAttributes()) : 
  could not find function "editDialogServer"`

**Comment by beerda** [comment]
I'm sorry, I know about it, the project is in its very initial phase, I am renaming the functions to some more convenient names and I have accidentally pushed the unfinished work. I will fix it tomorrow :-)

**Comment by beerda** [comment]
Fixed
