### ISSUE TITLE
access data

### ISSUE THREAD

**Issue by cherif40** [beerda/crudtable#2]
Thanks for this great package, but I have a problem to use the data in oher shiny function.
Can you please show me an example how use the data in other shiny function.

**Comment by beerda** [comment]
Hi, I do not understand your question. What do  you mean by the "other shiny function"? Can you provide a code example of your problem?

**Comment by cherif40** [comment]
ui <- navbarPage("Test",
    tabPanel("CRUD", crudTableUI('crud')),
    tabPanel("Plot", plotlyOutput('VT'))
)

# Server-side
server <- function(input, output, session) {
    callModule(crudTable, 'crud', dao, myFormUI, myFormServer)

    output$VT <- renderPlotly({
        plot_ly(--- ,  x = ~DateEch, y = ~T, split= ~milieu, size= ~T )  %>%
            add_markers(linetype = ~Stations) #
    })
}

**Comment by cherif40** [comment]
prodRegions2 <- read_delim("instm_bizerte.csv",
                           ";", escape_double = FALSE, col_types = cols(DateEch = col_date(format = "%d/%m/%Y")),
                           trim_ws = TRUE)

con <- dbConnect(RSQLite::SQLite(), "bdata20.sqlite")


# Register database cleanup on stop of the shiny app
shiny::onStop(function() { dbDisconnect(con) })

# Create an empty data frame

#####################################
df <-  data.frame(
           DateEch =  numeric(),
           Stations = character(),
           Type = character(),
           Lon = numeric(),
           Lat = numeric(),
           T = numeric(),
           S = numeric(),
           Cond = numeric(),
           O2 = numeric(),
           pH = numeric(),
           Depth = numeric(),
           Turbidite = numeric(),
           NO2 = numeric(),
           NO3 = numeric(),
           NH4 = numeric(),
           PO43 = numeric(),
           Si = numeric(),
           NT = numeric(),
           PT = numeric(),
           Chla = numeric(),
           DIN = numeric(),
           DIP = numeric(),
           milieu = character(),
           date = numeric(),

           stringsAsFactors = FALSE)
###########################################

# Save the data frame into SQLite as table 'invoice'
dbWriteTable(con, 'invoice', df, overwrite = FALSE, append = TRUE)

# dbWriteTable(con, "invoice", prodRegions2, overwrite = FALSE, append = TRUE)


# Create a Data Access Object
dao <- sqlDao(con,
              table = 'invoice',
              typecast = list(date=typecastDateToNumeric(),
                              DateEch=typecastDateToNumeric()))





#########################################################################
# 3. Edit form user interface definition
#########################################################################

# Create edit form dialog
myFormUI <- function(id) {
    ns <- NS(id)
    formUI(id,
           dateInput(ns("DateEch"),"Date Echant", ""),
           textInput(ns("Stations"),"Station", ""),
           selectInput(ns("Type"), "Type","S"),
           numericInput(ns("Lon"), "Longitude", 36),
           numericInput(ns("Lat"), "Latitude", 9),
           numericInput(ns("T"), "Temperature", 9),
           numericInput(ns("S"), "Salinite", 9),
           numericInput(ns("Cond"), "Conductivite", 9),
           numericInput(ns("O2"), "Oxygene", 9),
           numericInput(ns("pH"), "pH", 9),
           numericInput(ns("Depth"), "Depth", 9),
           numericInput(ns("Turbidite"), "Turbidite", 9),
           numericInput(ns("NO2"), "NO2", 9),
           numericInput(ns("NO3"), "NO3", 9),
           numericInput(ns("NH4"), "NH4", 9),
           numericInput(ns("PO43"), "PO43", 9),
           numericInput(ns("Si"), "Si", 9),
           numericInput(ns("NT"), "NT", 9),
           numericInput(ns("PT"), "PT", 9),
           numericInput(ns("Chla"), "Chla", 9),
           numericInput(ns("DIN"), "DIN", 9),
           numericInput(ns("DIP"), "DIP", 9),
           textInput(ns("milieu"), "milieu", 9),
           dateInput(ns("date"),"date", "")
    )
}


#########################################################################
# 4. Initialize the default server-side form handler
#########################################################################

# Create standard edit form dialog handler that will be used in a custom handler
defaultFormServer <- formServerFactory(
    dao = dao

)

#########################################################################


#########################################################################
# 5. Create custom server-side form handler
#########################################################################

# Create custom edit form dialog handler
myFormServer <- function(input, output, session) {
    # first do the default behaviour
    res <- defaultFormServer(input, output, session)

    res
}


#########################################################################
# 6. Shiny app initialization
#########################################################################



ui <- navbarPage("Test",
    tabPanel("CRUD", crudTableUI('crud')),
    tabPanel("Plot", plotlyOutput('VT'))
)

# Server-side
server <- function(input, output, session) {
    callModule(crudTable, 'crud', dao, myFormUI, myFormServer)

    output$VT <- renderPlotly({
        plot_ly(dao, x = ~DateEch, y = ~T, split= ~milieu, size= ~T )  %>%
            add_markers(linetype = ~Stations) 
    })
}

# Run the shiny app
shinyApp(ui = ui, server = server)

?) Problem with output$VT

**Comment by cherif40** [comment]
I have resolve the problem with loadData function
Thanks

**Comment by cherif40** [comment]
Hi,
After using your package for the CRUD part, I used the loadData () function to inject the data into other functions such as:

output $ scatter <- renderPlotly ({
         plot_ly (loadData (), x = ~ Date, split = ~ middle, type = "scatter", size = ~ get (input $ ysizecol))
   })

the problem with the Date variable, it displays it as a real value.
Is there a solution to correct the display of the date variable?

Here is the loadData () function:
# loadData ()
table <- 'invoice'
loadData <- function () {
   # Connect to the database
   con <- dbConnect (RSQLite :: SQLite (), "bdata20.sqlite")
  
   # Construct the fetching query
   query <- sprintf ("SELECT * FROM% s", table)
   # Submit the fetch query and disconnect
   data <- dbGetQuery (con, query)
   dbDisconnect (con)
   data
}
thanks a lot for your help

**Comment by beerda** [comment]
I guess this is a problem of rsqlite since it does not support complex data types such as Date. That is, rsqlite transforms internally the Date object to a numeric value before it is stored in the SQL table. The crudtable package takes care of transforming that numbers back to Date on load, but since you are loading the data manually by using the SQL commands directly, you have to either typecast the number to date manually, or, preferably, to use the crudtable's DAO object to load your data for you. Perhaps you may rewrite your loadData() function to call dao$getData() to obtain the data. There will be no need to fiddle with SQL queries by yourself and also the typecasting of the Date columns will take place.

Anyway, thank you for pointing out that use case, I should provide a more convenient mechanism that will allow to connect the DAO object as an reactive input to some shiny outputs. I will do that in some future version of the crudtable package.

**Comment by cherif40** [comment]
It works well, thank you very much.

**Comment by beerda** [comment]
I have updated the crudtable package to follow the new module mechanism of shiny 1.5.0. In the advanced example (examples/advanced/app.R) you can see how to update the output widgets automatically once the data in the CRUD table change (see the dataChangeTrigger reactive value)
