### ISSUE TITLE
crud on several tables

### ISSUE THREAD

**Issue by cherif40** [beerda/crudtable#3]
Hello Beerda,
Thank you first of all for your work and the improvement you add to the crudtable package, it is very interesting.
I have a question if you allow me: is it possible to apply the crud on several tables in the database?

**Comment by beerda** [comment]
Hi,
using the crudtable on multiple tables in the database is the goal of the project. However, I have not yet experimented with such scenario. Using crudtable on two or more separate tables should not be a problem, IMHO the modularity provided by Shiny should allow that easily. Of course, to use tables connected via the primary/foreign key is a more interesting scenario. I plan to work on it in the future. Nowadays, I am still working on the basic programming interface to the whole package, so beware, the basic functions and objects will change.

**Comment by cherif40** [comment]
Hi,
thank you for your reply. 
I am in the case of a separate table, can you clarify me better about  'IMHO the modularity provided by Shiny'.

**Comment by beerda** [comment]
I mean basically the following:

```
library(shiny)
library(crudtable)

# Data Access Object from the CO2 data frame
dao <- dataFrameDao(CO2)
dao2 <- dataFrameDao(CO2)

# User Interface
ui <- fluidPage(
    crudTableUI('crud'),
    crudTableUI('crud2')
)

# Server-side
server <- function(input, output, session) {
    crudTableServer('crud', dao)
    crudTableServer('crud2', dao2)
}

# Run the shiny app
shinyApp(ui = ui, server = server)
```

In this example:
1. two separate DAO objects are created (initially both containing the same table, but you can connect them to anything you want);
2. two crudtable UIs are created (you can put them into separate tab panels or wherever)
3. both crud UIs are processed on the server-side.

**Comment by cherif40** [comment]
Good job, thank you 👍
